name: etc
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm

  # Step: DB
  - pymongo
  - sqlalchemy
  - redis

  # Step: Queue
  - rq

  # Step: API
  - Flask-API
  - fastapi