name: etc
channels:
  - defaults
  - conda-forge
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm
  - pytest

  # Step: DB
  - pymongo
  - sqlalchemy
  - redis

  # Step: Queue
  - rq

  # Step: API
  - Flask-API
  - fastapi