name: geo_tiles2
channels:
  - conda-forge
dependencies:
  # Step: Jupyter Common
  - python
  - pip
  - setuptools
  - wheel
  - jupyter
  - jupyter_contrib_nbextensions
  - nbdime
  - tqdm

  # Step: Science
  - numpy
  - pip:
      - git+https://github.com/numpy/numpy-stubs#egg=numpy-stubs
  - matplotlib
  - seaborn
  - SciPy
  # SciKits (short for SciPy Toolkits) are add-on packages for SciPy
  # Description https://www.scipy.org/scikits.html
  # List of available kits http://scikits.appspot.com/scikits
  - scikit-learn

  # Step: Pandas
  # Recommended dependencies
  # https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#recommended-dependencies
  - pandas
  - numexpr
  - bottleneck
  # Additional packages for Pandas
  - pip:
      - git+https://github.com/mouradmourafiq/pandas-summary#pandas-summary
  # Optional dependencies
  # https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies
  - PyTables
  - SciPy
  - blosc
  - fastparquet
  - numba
  - pyarrow
  - pytables
  - zlib

  # Step: Files and Images
  - h5py # HDF5
  - pillow # PNG, JPEG and image operations
  - pip:
      - tifffile # TIFF
      - imagecodecs # for tifffile

  # Step: Geo Coords Transform
  - mercantile