name: flask
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm

  # Step: Web Common
  - urllib3
  - requests

  # Step: Flask
  - Flask
  - Jinja2
  - Werkzeug

  # Step: Additional Packages for Flask
  - flask-wtf
  - flask-bootstrap

  # Step: Mongo
  - pymongo