name: flask
channels:
  - default
  - conda-forge
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm
  - pytest

  # Step: Network
  - requests
  - urllib3

  # Step: Flask
  - Flask
  - Jinja2
  - Werkzeug

  # Step: Additional Packages for Flask
  - flask-wtf
  - flask-bootstrap

  # Step: Mongo
  - pymongo