name: jupyter_common
channels:
  - defaults
  - conda-forge
dependencies:
  # Step: Jupyter Common
  - python
  - pip
  - setuptools
  - wheel
  - jupyter
  - jupyter_contrib_nbextensions
  - nbdime
  - tqdm
  - pytest