name: web
channels:
  - default
  - conda-forge
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm
  - pytest

  # Step: Networks
  - requests
  - urllib3

  # Step: AsyncIO
  - aiohttp
  - aiofiles

  # Step: Mongo
  - pymongo

  # Step: API
  - fastapi