name: jupyter_common
dependencies:
  # Step: Common
  - python
  - tqdm

  # Step: Web
  - urllib3
  - requests

  # Step: AsyncIO
  - aiohttp
  - aiofiles

  # Step: Mongo
  - pymongo

  # Step: API
  - fastapi