name: web
dependencies:
  # Step: Common
  - python
  - pip
  - setuptools
  - wheel
  - tqdm

  # Step: Web Common
  - urllib3
  - requests

  # Step: AsyncIO
  - aiohttp
  - aiofiles

  # Step: Mongo
  - pymongo

  # Step: API
  - fastapi